// Collects t('…') literals from the Vue admin and writes a PHP file that
// passes each through __() (see src/i18n.js). Run automatically by `npm run build`.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, '..', 'src');
const outFile = join(here, '..', '..', 'includes', 'admin', 'admin-app-strings.php');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return walk(p);
    return /\.(vue|js)$/.test(name) ? [p] : [];
  });
}

// t('...') / t("...") — literal only (no template interpolation).
const re = /\bt\(\s*(['"])((?:\\.|(?!\1).)*)\1/g;
const strings = new Set();
for (const file of walk(srcDir)) {
  const code = readFileSync(file, 'utf8');
  let m;
  while ((m = re.exec(code))) {
    const raw = m[2];
    // Unescape JS string escapes (\' \" \\ \n).
    const val = raw.replace(/\\(['"\\])/g, '$1').replace(/\\n/g, '\n');
    if (val.trim()) strings.add(val);
  }
}

const phpQuote = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const lines = [...strings].sort((a, b) => a.localeCompare(b)).map(
  (s) => `\t${phpQuote(s)} => __( ${phpQuote(s)}, 'woo-smart-search' ),`
);

const php = `<?php
/**
 * Admin panel (Vue) strings, generated by admin-app/scripts/extract-i18n.mjs.
 * Do not edit by hand: run \`npm run build\` in admin-app/.
 *
 * @package WooSmartSearch
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
${lines.join('\n')}
);
`;
writeFileSync(outFile, php);
console.log(`extract-i18n: ${strings.size} strings -> ${outFile}`);
